### ISSUE TITLE
Style the `<SiteNavbar />` component

### ISSUE THREAD

**Issue by erunks** [speedrun-website/speedrun.website#6]
## What
Thanks to this PR https://github.com/speedrun-website/speedrun.website/pull/5. We have [Tailwind](https://tailwindcss.com) setup and a functional `<SiteNavbar />` component. Now we want to make it match our wireframes.

## Wireframe
https://www.figma.com/file/DNCMCfWjft4poxGIgJSHyA/Wireframes?node-id=9%3A27

## Acceptance
Have our newly created `<SiteNavbar />` match our wireframes for both the Mobile and Desktop designs.

**Comment by NexusX45** [comment]
Hi there, can I contribute to your repo?

**Comment by erunks** [comment]
Sure! We're currently working on getting a `CONTRIBUTING.md` doc up on the repo. In the mean time, just fork the main repo and make all your issue related commits there. Then just open a PR against the `main` branch of this repo. If you need any more guidance or if an issue is unclear, drop into [the discord for this project](https://discord.gg/TZvfau25Vb) and ask around for some help.
